apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluen-flux-v2
  namespace: flux-system
  annotations:
    cloud.altitude.com/opa-check-disabled: 'true'
spec:
  targetNamespace: flux-v2-tests
  interval: 1m0s
  chart:
    repository: https://confluentinc.github.io/cp-helm-charts/
    name: cp-helm-charts
    version: 0.5.0
  values:
    cp-zookeeper:
      persistence:
        dataDirSize: 16Gi
        dataDirStorageClass: ssd-standard 
        dataLogDirSize: 16Gi
        dataLogDirStorageClass: ssd-standard
    cp-kafka: 
      persistence:
        storageClass: ssd-standard
        size: 32Gi
      configurationOverrides:
        "offsets.topic.replication.factor": 3
        "default.replication.factor": 3
        "min.insync.replicas": 2
        "auto.create.topics.enable": false
    cp-kafka-connect:
      image: altituderegistry.azurecr.io/altitude-global-kafka-connect
      imageTag: 1.2.0
    cp-control-center:
      enabled: false
