---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/dmourao/flux-v2-tests
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: confluentinc
  namespace: flux-system
spec:
  interval: 10m0s
  url: https://confluentinc.github.io/cp-helm-charts/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
---
#---
# kind: Secret
# apiVersion: v1
# metadata:
#   name: msteams-url
#   namespace: flux-system
# data:
#   address: >-
#     aHR0cHM6Ly9vdXRsb29rLm9mZmljZS5jb20vd2ViaG9vay9jODM5MDgyMC1hZGM2LTQyOTEtYmMxZC03NTViYmE5Y2NlYmJAZTRkYTY1NDctYzQ4ZS00NDFhLWEyMzYtNjU2NjVlZjA1NGQxL0luY29taW5nV2ViaG9vay83NzUzZTQ3MmE1OGQ0NWM2OTQzMTcyYWQ5NGFlNWRlZC81ZjI1NTcwMi01ODkyLTQxYTEtYTgxMy01M2MxMmNjNThiOTA=
# type: Opaque
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: msteams
  namespace: flux-system
spec:
  channel: FluxCloudTest
  secretRef:
    name: msteams-url
  type: msteams
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call
  namespace: flux-system
spec:
  providerRef:
    name: msteams
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
  suspend: true